### PR TITLE
Add link to ufront guides

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by skial** [comment]
Holy crap, how did I _**not**_ link to your guide!?! Sorry @kevinresol!

**Comment by kevinresol** [comment]
No problem, we are just human :smile:

**Comment by skial** [comment]
Somehow forgetting to add a link to your guide defeats the purpose of my todo lists - https://github.com/skial/haxe.io/issues/258#issuecomment-196736368 - which _links_ to your guide! :anguished:

**Comment by skial** [comment]
The update should have finished propagating to all cdn edges. Thanks again @kevinresol.

**Pull request merged**
