### PR TITLE
Fix frontpage readability (closes #141) + a few other minor improvements

### LINKED ISSUE #141: Bad contrast / readability on the frontpage
The white texts on the homepage rarely contrast well against the background images, making it really hard to read most of the time. A black outline or something might help.

### PR DESCRIPTION
**Pull request by Gama11**
It's a lot darker now, but I think it works (definitely better than before).

### CODE REVIEW

**Comment by Gama11** [comment]
I've only tested the .css in the Chrome debugger, so I'm not sure how it looks like in other browsers or when re-generating the site.

**Comment by skial** [comment]
Hey @Gama11, just a quick note that I'm not ignoring this. I will get around to reviewing this in the next week :wink:

**Comment by Gama11** [comment]
No problem, thanks for the update!

**Comment by skial** [comment]
- I don't think removing `The Haxe` from the LD posts is needed, unless `Haxe` is removed from `Haxe Roundup № 123` as its all hosted on `haxe.io` it _should_ be obvious that its going to be Haxe related?
- I agree with `Luxe Engine => Luxe`.
- I'm not sure about `Correct this => Edit this`
- The frontpage is much more readable, I'll pull it locally to try a few ideas.

@Gama11 sorry for taking almost 2 weeks to reply, I didn't intend to take so long!

**Comment by Gama11** [comment]
To be honest, the main reason for removing `The Haxe` from those was that that makes the titles short enough to fit into a single line - two lines looks inconsistent / not that great with the black backgrounds of the new style.

**Comment by Gama11** [comment]
What happened to the frontpage improvements?

**Comment by skial** [comment]
Me and a lack of time.

I'm also behind on the latest roundup
<https://github.com/skial/haxe.io/issues/175>, I've had a combined hour
over the last week to get afew lines written down.

**Comment by Gama11** [comment]
I see - no worries! :)

I could help out a bit - with the ludum dare 33 roundup maybe?

**Comment by skial** [comment]
Sure, that would be awesome!

**Comment by nadako** [comment]
I'd love this (or something like) to be merged. It's quite a pain reading white text on top of a picture.

**Comment by skial** [comment]
Ok, I've pulled my finger out and used a slightly modified version of @Gama11 css changes. Hopefully its better for most people. See https://github.com/skial/haxe.io/pull/143.

I need to stop being a perfectionist and get an improved haxe.io sooner than never :wink:

**Pull request closed without merging**
