### PR TITLE
Update 372.md

### PR DESCRIPTION
**Pull request by Laguna1989**
I added a link to a tutorial I wrote at the beginning of october.

### CODE REVIEW

**Comment by skial** [comment]
Thanks @Laguna1989 for the link, I'll give you have two options, have the tutorials added to 372 or wait until next weeks for a fresh set of eye balls?

**Comment by Laguna1989** [comment]
Hi there,
If it is no problem, i would like the Link to be added for the next Roundup.
Best regards
Simon Weis
Am 01.11.2016 09:43 schrieb Skial Bainn <notifications@github.com>:Thanks @Laguna1989 for the link, I'll give you have two options, have the tutorials added to 372 or wait until next weeks for a fresh set of eye balls?

**Comment by skial** [comment]
No problem at all, its been added to #353.

**Comment by Laguna1989** [comment]
wohoo :)

**Pull request closed without merging**
