### PR TITLE
Improved? styling

### PR DESCRIPTION
**Pull request by skial**
See [dev.haxe.io/roundups/352/](http://dev.haxe.io/roundups/352/index.html) for current design.

### CODE REVIEW

**Comment by skial** [comment]
- [ ] [ osx el capitan safari 9](https://saucelabs.com/tests/37c24689a47b4b3f9b1e433fecedb6fb), ipad retina sim, [ipad retina ios 9.2](https://saucelabs.com/tests/6394f41a01cc48e4af83f9cde12829c4) - frontpage logo not displaying - svg filter?
- [ ] [ipad retina ios 9 sim](https://saucelabs.com/tests/0db005cca49f47d480e22201c6adda34) - filter buttons do not work until rotated, then stuck on selection?
- [ ] [android 4.2 emulator](https://saucelabs.com/tests/37f3a66de0b641759184bd7cdc101379) - wtf!?

**Comment by skial** [comment]
Majority of content replicated on [dev.haxe.io](http://dev.haxe.io) now.

**Comment by skial** [comment]
Nav items should be centred.

screenshot 2016-05-02 19 41 59

**Comment by 5Mixer** [comment]
Hey, nice work! Here is some random feedback:

 -  On mobile (and potentially desktop) the 'filter by' text is not left aligned, like the individual filters. Also, the 'suggest a link' button inside the view for round ups is in a weird spot.

- The last design distinguished between round ups with images from the post. With this design, the round ups appear the same, except for a number. A number isn't too identifiable, but the images were. I'm not sure how you would counter this, if you were to, but it's food for thought anyway.

- Allow an option for showing more than one column at once. This is such a minor point, because generally users will just want the latest post. Anyway, you could do something similar to unsplash, where by default it is one column, but a button allows for multiple columns (like the old design)

Overall, the new style is really cool. The colour and font choices in the roundups is very neat. Great work as usual, you really help the Haxe community.

**Comment by skial** [comment]
Thanks @5Mixer for the feedback.

> On mobile (and potentially desktop) the 'filter by' text is not left aligned, like the individual filters.

I'll look into this.

> the 'suggest a link' button inside the view for round ups is in a weird spot.

Yep, I'm still trying to figure out why flexbox is doing this :/ See https://github.com/skial/haxe.io/pull/277#issuecomment-216240673 `[mobile]` comment.

> ... the round ups appear the same, except for a number. A number isn't too identifiable ...

Good point, I've got some ideas I can experiment with.

> Allow an option for showing more than one column at once

Do you mean -

1. allow more than one filter to be selected at the same time?
1. for each selected filter, create a new column?

For 1. you can already select multiple filters. For 2., this might need a js solution, so far everything has mainly been css only, with very minor html changes here and there.

Sorting by oldest is easy with flexbox, but by most popular, that would again need a js solution, with analytics data being processed etc etc. Possible future addition...

> Overall, the new style is really cool. The colour and font choices in the roundups is very neat.

Thanks, its about time the _harsh_ colour scheme got replaced :wink:

**Comment by 5Mixer** [comment]
> Do you mean...

Never mind haha, it turns out what I said only applies to mobile :) I meant that because (on the iPad) there is just one large, wide, roundup in a row, you have to scroll down and the view is very plain. On desktop I can see the different sized boxes side by side. What I saw: https://i.gyazo.com/ccecbc7ec4cfc7eed39bdef14a830073.png. You don't need to change anything there :)

The sort by popularity would be nice, but I wouldn't spend ages on it. The filters you have intergrated are already a large improvement from the old version.

**Comment by skial** [comment]
I'll see if changing the width on the 2nd+ items works out ok.

**Comment by ConfidantCommunications** [comment]
Hi Skial—I'm wondering if we could do anything to make it easier to scan visually when dozens of items are on the page, i.e. how can I quickly ascertain whether I want to choose #250 versus #54? It seems like images are coming eventually; is there any way to also add a bit of intro text without it getting too cluttered? A table layout comes to mind.

**Comment by skial** [comment]
Hey @ConfidantCommunications,

> I'm wondering if we could do anything to make it easier to scan visually when dozens of items are on the page, i.e. how can I quickly ascertain whether I want to choose no.250 versus no.54?

Yeah thats a bigger problem that needs solving. I would love to have searching implemented but I don't know how to do this. Ideally self hosted, with full control over the formatting/styling.

I have some ideas that could help in giving an idea whats contained in each roundup, but this would likely have to be limited to some extent, which then hides other content. :confused: 

> It seems like images are coming eventually

At the moment, with this pr, I'm more focused on an improved styling, with very minimal html changes. I think at the moment only the frontpage and the videos/events templates have html changes, everything else is css.

The images will return once I've got an acceptable, aggressive, way to optimise images into various formats, sizes etc etc. That's the next step, as images are my main cdn cost.

> is there any way to also add a bit of intro text without it getting too cluttered

For the majority of frontpage items, there is a small text field, usually the same as the first paragraph of the article, but they are currently `display: none`. :smile: Currently I haven't found a way I'm happy with to incorporate them, but I do want to bring them back.

**Comment by skial** [comment]
Thanks @5Mixer & @ConfidantCommunications for adding your thoughts, it's really appreciated and a great help.

**Comment by ConfidantCommunications** [comment]
Glad to do so; thanks for your invaluable contribution to our community!

**Comment by skial** [comment]
For testing performance.
- http://dev.haxe.io/ for non-gzipped, partially minified content.
 - http://dfzy0zhi97d76.cloudfront.net gzipped version of dev.haxe.io.
- http://opt.haxe.io/ for non-gzipped, with various optimisations applied.
 - http://d2zb6f8q2egda.cloudfront.net gzipped version of opt.haxe.io

This only applies to `html` and `css` content.

**Comment by 5Mixer** [comment]
Works well! Tiny thing I picked up, not sure if you already know about it, but the p in Roundup is overflowing from the box, atleast on mobile.

**Comment by skial** [comment]
> ...the p in Roundup is overflowing from the box, at least on mobile.

I forgot to note that down! Thanks for reminding me @5Mixer!

**Comment by markknol** [comment]
My suggestions;
* Make each box in the overview clickable, not only the text.
* Are the images in the overview gone?
* I thing the typography can be improved. Personally I think the haxe.io font isn't nice or does not align nice with the logo. Also the h1's are [very big](https://cloud.githubusercontent.com/assets/576184/15144686/594eb17e-16b1-11e6-923d-e1c0b44106db.png)
* Maybe add a back-to-top button in footer.
* Maybe you can add _some_ Haxe style related elements to make it more Haxe? (I know its not an official HF thing but this is _the_ source of news :+1: :+1: )

I like the filters! I also like how you style links based on its website, very clever.

**Comment by skial** [comment]
Hey @markknol, thanks for the feedback :+1: 

> Make each box in the overview clickable, not only the text.

I havent looking into this yet, but I will.

> Are the images in the overview gone?

No, they will come back at some point, but having so many on one page and not being optimised in any way was stupid. This will be the next area I look at, once I've finished this pr.

> I think the typography can be improved. Personally I think the haxe.io font isn't nice or does not align nice with the logo

I have seen other I like, I will try them out. What don't you like about the font?

> Also the h1's are very big

Yep, I do like them :smile: but it is a waste of space. They are likely to remain _**large**_ to some extent!

> Maybe add a back-to-top button in footer.

Good idea.

> Maybe you can add some Haxe style related elements to make it more Haxe? (I know its not an official HF thing but this is the source of news

That's actually something I'm going to look at _after_ I've sorted out my image optimisation pr.

> I also like how you style links based on its website, very clever.

Someone noticed! :smile:

**Comment by skial** [comment]
- [ ] Border on footer weirding out on firefox.

screenshot 2016-05-15 10 52 06

**Comment by skial** [comment]
:fire::fire::fire:

**Comment by markknol** [comment]
Boom :boom:

**Pull request merged**
