### PR TITLE
good old manual

### PR DESCRIPTION
**Pull request by markknol**
The "Good old manual" is not the old site/documentation, it is the manual :)

### CODE REVIEW

**Comment by skial** [comment]
Really?! I hadn't considered the manual as old.

**Comment by markknol** [comment]
Ok I guess/hope/believe he means the actual manual, not the old wiki.

**Comment by skial** [comment]
I can always change it if its wrong :wink: 

cc @nadako

**Comment by markknol** [comment]
I stop doing everything on the documentation when he means the old wiki :stuck_out_tongue_winking_eye:

**Pull request merged**
